package io.github.ugaikit.gemini4kt.live.music

import kotlinx.serialization.Serializable

// --- Client Messages ---

/**
 * Message to be sent in the first (and only in the first) LiveMusicClientMessage.
 * Clients should wait for a LiveMusicSetupComplete message before sending any additional messages.
 */
@Serializable
data class LiveMusicClientSetup(
    val model: String? = null,
)

/**
 * Maps a prompt to a relative weight to steer music generation.
 */
@Serializable
data class WeightedPrompt(
    val text: String? = null,
    val weight: Double? = null,
)

/**
 * User input to start or steer the music.
 */
@Serializable
data class LiveMusicClientContent(
    val weightedPrompts: List<WeightedPrompt>? = null,
)

/**
 * Configuration for music generation.
 */
@Serializable
data class LiveMusicGenerationConfig(
    val temperature: Double? = null,
    val topK: Int? = null,
    val seed: Int? = null,
    val guidance: Double? = null,
    val bpm: Int? = null,
    val density: Double? = null,
    val brightness: Double? = null,
    val scale: Scale? = null,
    val muteBass: Boolean? = null,
    val muteDrums: Boolean? = null,
    val onlyBassAndDrums: Boolean? = null,
    val musicGenerationMode: MusicGenerationMode? = null,
)

/**
 * Messages sent by the client in the LiveMusicClientMessage call.
 */
@Serializable
data class LiveMusicClientMessage(
    val setup: LiveMusicClientSetup? = null,
    val clientContent: LiveMusicClientContent? = null,
    val musicGenerationConfig: LiveMusicGenerationConfig? = null,
    val playbackControl: LiveMusicPlaybackControl? = null,
)

// --- Server Messages ---

/**
 * Sent in response to a LiveMusicClientSetup message from the client.
 */
@Serializable
class LiveMusicServerSetupComplete

/**
 * Prompts and config used for generating this audio chunk.
 */
@Serializable
data class LiveMusicSourceMetadata(
    val clientContent: LiveMusicClientContent? = null,
    val musicGenerationConfig: LiveMusicGenerationConfig? = null,
)

/**
 * Representation of an audio chunk.
 */
@Serializable
data class AudioChunk(
    val data: String? = null, // Base64 encoded bytes
    val mimeType: String? = null,
    val sourceMetadata: LiveMusicSourceMetadata? = null,
)

/**
 * Server update generated by the model in response to client messages.
 */
@Serializable
data class LiveMusicServerContent(
    val audioChunks: List<AudioChunk>? = null,
)

/**
 * A prompt that was filtered with the reason.
 */
@Serializable
data class LiveMusicFilteredPrompt(
    val text: String? = null,
    val filteredReason: String? = null,
)

/**
 * Response message for the LiveMusicClientMessage call.
 */
@Serializable
data class LiveMusicServerMessage(
    val setupComplete: LiveMusicServerSetupComplete? = null,
    val serverContent: LiveMusicServerContent? = null,
    val filteredPrompt: LiveMusicFilteredPrompt? = null,
)

// --- Enums ---

@Serializable
enum class Scale {
    SCALE_UNSPECIFIED,
    C_MAJOR_A_MINOR,
    D_FLAT_MAJOR_B_FLAT_MINOR,
    D_MAJOR_B_MINOR,
    E_FLAT_MAJOR_C_MINOR,
    E_MAJOR_D_FLAT_MINOR,
    F_MAJOR_D_MINOR,
    G_FLAT_MAJOR_E_FLAT_MINOR,
    G_MAJOR_E_MINOR,
    A_FLAT_MAJOR_F_MINOR,
    A_MAJOR_G_FLAT_MINOR,
    B_FLAT_MAJOR_G_MINOR,
    B_MAJOR_A_FLAT_MINOR,
}

@Serializable
enum class MusicGenerationMode {
    MUSIC_GENERATION_MODE_UNSPECIFIED,
    QUALITY,
    DIVERSITY,
    VOCALIZATION,
}

@Serializable
enum class LiveMusicPlaybackControl {
    PLAYBACK_CONTROL_UNSPECIFIED,
    PLAY,
    PAUSE,
    STOP,
    RESET_CONTEXT,
}
