# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on: [push]

env:
  GEMINI_API_KEY : ${{ secrets.GEMINI_API_KEY }}

jobs:
  build:
    strategy:
        matrix:
          java_version: [17, 21, 23]
    runs-on: ubuntu-latest
    
    steps:
      - name: Use a secret
        run: echo "My secret is ${{ secrets.GEMINI_API_KEY  }}"
      - uses: actions/checkout@v4.2.1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4.4.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0
      - name: Build with Gradle
        run: ./gradlew build run
